name = "bus-rollcall-backend"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "bus-rollcall-db"
database_id = "07f18294-9815-41fb-adc9-9186ee4ee1f6"

# Secrets like JWT_SECRET should be set via the Cloudflare Dashboard
# or using 'wrangler secret put JWT_SECRET'
# [vars]
# JWT_SECRET = "..."
[secrets]
required = ["JWT_SECRET"]


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1