name = "bus-rollcall-backend"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "bus-rollcall-db"
database_id = "c05d960e-2a56-47b5-89d4-b0e24ef7db94"
